version: '3'
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile-Tomcat
    volumes:
      - ./files/tomcat/etc/supervisord.d/:/etc/supervisord.d

  code:
    build:
      context: ../
      dockerfile: Dockerfile-demo
    volumes:
      - ../:/code
      - ./files/code/etc/ssh/ssh_config:/etc/ssh/ssh_config
      - ./files/code/etc/ansible/roles:/etc/ansible/roles
